### ISSUE TITLE
space bar

### ISSUE THREAD

**Issue by mallimuondu** [muondu/Election-Platform#3]
nimeingia then i clicked space bar

Good morning

    Who do you want to be
    a Voter
    b Candidate
    c Staff member

    Choose any of them:  
    
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    which_person_function()
  File "main.py", line 21, in which_person_function
    """)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

Makit work

**Comment by mallimuondu** [comment]
nothing works
when it ask me ati are you a voter or a candidate or staff then I choose anything it doesn't work
it says
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    which_person_function()
  File "main.py", line 21, in which_person_function
    """)
  File "<string>", line 1, in <module>
NameError: name 'a' is not defined

**Comment by muondu** [comment]
It has no error @mallimuondu.


For the first issue
